version: '3.8'
services:
  frontend:
    image: nginx:alpine
    volumes:
      - ../:/var/www/bsenem
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "127.0.0.1:8081:80"
    depends_on:
      - api
    restart: unless-stopped

  api:
    image: php:8.2-cli
    volumes:
      - ../:/var/www/bsenem
    working_dir: /var/www/bsenem/backend/api
    command: php -S 0.0.0.0:8000 index.php
    restart: unless-stopped
